#!/usr/bin/env python3
"""Build native Rive paths from the requested Google Fonts Noto Sans TC web font.

Run with --download when the Chinese character set changes, otherwise the
checked-in WOFF2 is sufficient. Requires fonttools[woff] (including brotli).
"""
import argparse
import hashlib
import json
import re
from pathlib import Path
from urllib.parse import urlencode
from urllib.request import Request, urlopen

from fontTools.pens.basePen import BasePen
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'assets' / 'fonts'
FONT = ASSETS / 'noto-sans-tc-700.woff2'


def fetch(url):
    request = Request(url, headers={'User-Agent': 'Mozilla/5.0 AppleWebKit/537.36 Chrome/131.0.0.0 Safari/537.36'})
    with urlopen(request, timeout=45) as response:
        return response.read()


class RivePen(BasePen):
    def __init__(self, glyph_set, upem):
        super().__init__(glyph_set)
        self.upem = upem
        self.commands = []

    def point(self, point):
        x, y = point
        return f'{x / self.upem * 6:.4f} {(0.88 - y / self.upem) * 6:.4f}'

    def _moveTo(self, p):
        self.commands.append('M ' + self.point(p))

    def _lineTo(self, p):
        self.commands.append('L ' + self.point(p))

    def _curveToOne(self, a, b, c):
        self.commands.append('C ' + ' '.join(map(self.point, (a, b, c))))

    def _qCurveToOne(self, a, b):
        # Use cubics throughout: the local Rive script renderer drops portions
        # of quadratic font contours. This conversion preserves the exact curve.
        start = self._getCurrentPoint()
        c1 = tuple(start[i] + (a[i] - start[i]) * 2 / 3 for i in (0, 1))
        c2 = tuple(b[i] + (a[i] - b[i]) * 2 / 3 for i in (0, 1))
        self._curveToOne(c1, c2, b)

    def _closePath(self):
        self.commands.append('Z')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--download', action='store_true')
    args = parser.parse_args()
    source = '\n'.join((ROOT / name).read_text() for name in
                       ['localization.luau', 'remarks_catalog.luau'])
    chars = ''.join(sorted({c for c in source if ord(c) > 127}))
    if args.download:
        ASSETS.mkdir(parents=True, exist_ok=True)
        css_url = 'https://fonts.googleapis.com/css2?' + urlencode({
            'family': 'Noto Sans TC:wght@700', 'display': 'swap', 'text': chars})
        css = fetch(css_url).decode()
        url = re.search(r'url\((https://fonts.gstatic.com/[^)]+)\)', css).group(1)
        data = fetch(url)
        if data[:4] != b'wOF2':
            raise ValueError('Google Fonts did not return WOFF2')
        FONT.write_bytes(data)
        (ASSETS / 'OFL-NotoSansTC.txt').write_bytes(fetch('https://raw.githubusercontent.com/google/fonts/main/ofl/notosanstc/OFL.txt'))
        (ASSETS / 'noto-sans-tc-source.json').write_text(json.dumps({
            'family': 'Noto Sans TC', 'weight': 700, 'css_url': css_url, 'font_url': url,
            'sha256': hashlib.sha256(data).hexdigest(), 'characters': chars,
        }, ensure_ascii=False, indent=2) + '\n')
    font = TTFont(FONT)
    cmap = font.getBestCmap()
    missing = [c for c in chars if ord(c) not in cmap]
    if missing:
        raise ValueError(f'Missing glyphs {missing}; rerun with --download')
    glyphs = font.getGlyphSet()
    lines = ['-- Generated by tools/build_tc_font.py from Noto Sans TC Bold (Google Fonts WOFF2).',
             '-- SIL Open Font License: assets/fonts/OFL-NotoSansTC.txt. Do not edit by hand.',
             'return {']
    for char in chars:
        pen = RivePen(glyphs, font['head'].unitsPerEm)
        glyphs[cmap[ord(char)]].draw(pen)
        lines.append(f"    [{ord(char)}] = '{' '.join(pen.commands)}', -- {char}")
    lines.append('} :: { [number]: string }\n')
    (ROOT / 'tc_glyphs.luau').write_text('\n'.join(lines))
    print(f'Generated {len(chars)} Noto Sans TC glyphs from {FONT.stat().st_size:,} bytes of WOFF2')


if __name__ == '__main__':
    main()
